### ISSUE TITLE
Looping Task

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-frontend#130]
- [ ] Tabs for each instance of looping task
- [ ] "+ Add" button as first tab
- [ ] Scroll tabs if there are too many to fit in horizontal space
- [ ] Dock the Add button to the left edge of tab bar
- [ ] "x" button on each tab to remove task
- [ ] Confirmation dialog before removing

**Comment by danfunk** [comment]
A better ticket might be to combine the concept of looping tasks in the bpmn with the complex implementation we have now for repeating sections.  they both scratch the same itch, but are completely different things.
