### ISSUE TITLE
Stock enum field should return both Id and Name Values

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-frontend#135]
Currently if you specify an enum Form Field Type and provide Values, only the ID Value is available in the data dump to use.  The Name Value should be there as well.

- [x] Store all other lookup data with the value as well
- [x] Extend radio field to set value on change, reload, and hard reset
- [x] Extend multicheckbox field to set values on change, reload, and hard reset
- [x] Get unit tests passing

![image](https://user-images.githubusercontent.com/54854669/84319097-773c0b80-ab3d-11ea-81e2-e527eaa00bf2.png)
results in 
![image](https://user-images.githubusercontent.com/54854669/84319164-92a71680-ab3d-11ea-82e6-a985eca8c734.png)

**Comment by ajlouie** [comment]
@calexh-sar Regarding this issue, I'm trying to think of a way to implement it in a way that will be backwards-compatible with existing task data and scalable for the future.

Currently, enum field values are stored like this:
`"HavePersonnel": "no"`

But, if we stored them with their labels, it might look something like this:
```
"HavePersonnel": {
    value: "no",
    label: "No additional personnel, just myself, will be returning to the labs, workspaces and/or offices previously entered"
}
```

That means anything relying on the value of HavePersonnel being equal to "yes" or "no" would break.

So, if you had this Jinja template before:
`{% if HavePersonnel == "no" %}...{% endif %}`

You'd have to change it to this to retain backwards compatibility:
`{% if HavePersonnel == "or" or HavePersonnel.value == "no" %}...{% endif %}`

And, even then, you'd have to catch circumstances where the label hadn't been stored with the value.

So, the more scalable way to handle this might be to store the enum values and labels in a spreadsheet and retrieve the labels from the spreadsheet via a script task any time you need to use them in DMN or Jinja.

**Comment by calexh-sar** [comment]
I am pretty sure that anyplace I needed to refer to the data I had to change from the stock enum to spreadsheets.  So if that is the case, is there still a need for backwards compatibility?

**Comment by ajlouie** [comment]
Maybe? In the case of the `HavePersonnel` field in the `research_rampup.bpmn`, it's still a stock enum field. So it definitely would break any template that relied on its value being a string (`"no"`) rather than a dict or object (`{value: "no", label: "..."}`).

**Comment by calexh-sar** [comment]
Would I be able to "fix" anything related to fields like that before updated with a check for which format is available?

**Comment by ajlouie** [comment]
Not really (yet). We don't have an automated means of migrating all existing task data over to a completely new data model, since the structure of that data is defined by a combination of the form field definition and Formly, not by the database. So we can't do automated migrations.

**Comment by ajlouie** [comment]
I guess I answered the wrong question there.

You could definitely add a check in Jinja or the decision table for whether it's the old or new data structure. You'd have to remember which fields were defined before and after the change, though, and we'd definitely all forget that we even had this conversation several months later.

We'll all be scratching our heads wondering why the heck we have extra `if` conditions in everything.

**Comment by calexh-sar** [comment]
Was just restating the question, and you last answer addressed it.  Hopefully we can refer to this ticket so we don't scratch our heads too long.  So is "add(ing) a check in Jinja or the decision table for whether it's the old or new data structure" that a satisfactory path forward?

**Comment by ajlouie** [comment]
Yes, I think so. We'll just need to test the heck out of it and be watchful in the RRT production instance for any legacy data issues that arise because of this change.

**Comment by ajlouie** [comment]
- [ ] Store all other lookup data with the value as well
- [ ] Extend radio field to set value on change, reload, and hard reset
- [ ] Extend multicheckbox field to set values on change, reload, and hard reset
- [ ] Get unit tests passing

**Comment by ajlouie** [comment]
Depends on these other PRs:
- https://github.com/sartography/cr-connect-workflow/pull/137
- https://github.com/sartography/sartography-libraries/pull/13
