### ISSUE TITLE
Form rendering: Picklist

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-frontend#15]
One of the field types available in the current CRC is picklist.  Not sure if we need to duplicate this since it seems to be sparely used, but if easy to implement, we may want to consider.  

The one use of it I am aware of at this time is Collaborating Schools field in the "Study Organization(s) and Access, Study Titles" step.

![image](https://user-images.githubusercontent.com/54854669/71678395-10772280-2d53-11ea-934e-74323bc33870.png)

**Comment by ajlouie** [comment]
The multicheckbox form control takes the place of the pick list, since the default HTML multiple select has some very serious usability problems.
