### ISSUE TITLE
Display Study Associates

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect-frontend#186]
Kelly has a ticket currently underway to add tooling for adding and removing people from a study - setting whether they should receive communications from the system, or if they should have the right to access the system in some way.

This ticket is to surface these settings in the user interface.  

I suggest we add the individuals involved in the study to a separate tab on the bottom half of the Study Dashboard.  From there you can see the list of all study coordinators and other roles related to a study, and see their permissions.

**Comment by calexh-sar** [comment]
Will do at workflow level.
