### ISSUE TITLE
Ability to create and maintain data used elsewhere in application

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-frontend#22]
Sometimes data needed for the application is not available from outside sources in the format needed.  An example is this spreadsheet used by the current CRC:
[Award Owning Org Spreadsheet.xlsx](https://github.com/sartography/cr-connect-frontend/files/4099782/Award.Owning.Org.Spreadsheet.xlsx).

Allowing a Configurator to build out the data entry form , input and/or import data and maintain it for use in dynamic enum and lookup fields would be beneficial.

**Comment by calexh-sar** [comment]
@danfunk am I correct that the reference files feature recently satisfies this ticket?

**Comment by danfunk** [comment]
closed as per Alex's above comment.
