### ISSUE TITLE
Form renderer: Placeholder Help text not working

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-frontend#33]
The placeholder help text does not seem to be working as described.  The Label text is showing up in the body of the field instead of the placeholder text.

**Comment by ajlouie** [comment]
If you click into the field, the placeholder should appear as the label slides up to the left, according to [Google's Material Design guidelines](https://material.io/components/text-fields/). Apparently, they have usability research suggesting this is the way to do it... ¯\_(ツ)_/¯

**Comment by danfunk** [comment]
outdated.
