### ISSUE TITLE
Sponsors lookup 

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-frontend#51]
Ability to lookup sponsors stored in OSP spreadsheet and pull name and other needed information into system.

**Comment by calexh-sar** [comment]
[Sponsor sample for CRConnect 022520 (version 1).csv](https://drive.google.com/drive/folders/1lfEmt21cp-groNJYyd3kOambMSFrXYTS)

**Comment by calexh-sar** [comment]
@danfunk wasn't sure which repository you would be doing the back-end work in, but assume there will be front end work needed as well.

**Comment by ajlouie** [comment]
Fixed in https://github.com/sartography/cr-connect-frontend/commit/96d73bf6d95c758a4686b4485074782eda7fae49
