### ISSUE TITLE
Pass IRB Review - Documents & Approvals Screen

### ISSUE THREAD

**Issue by ajlouie** [sartography/cr-connect-frontend#55]
(see Victoria's designs)

- Protocol Upload
  - If not uploaded, link to upload protocol (Workflow Task screen)
  - If uploaded already:
    - Document file name
    - Status
    - Download file button
    - Delete file button

- Approvals
  - Title, linked to associated Workflow Task Form
  - Status
  - Contextual Help link to detail help page (blog?)

- Documents
  - Title, linked to associated Workflow Task Form
  - Approval Status
  - Contextual Help link to detail help page (blog?)
  - Download button

**Comment by danfunk** [comment]
outdated.
