### ISSUE TITLE
Include "by <user>" in last_updated message on study page

### ISSUE THREAD

**Issue by ajlouie** [sartography/cr-connect-frontend#61]
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a0e96bdb-6dc9-410e-88d9-6124d35813d8)

**Comment by cullerton** [comment]
We don't store the user information.
We need to decide whether/how we want to do that.
One possibility is to add a user column to file_data table.

**Comment by calexh-sar** [comment]
Working as designed.
