### ISSUE TITLE
Add support for subprocesses to workflow navigation

### ISSUE THREAD

**Issue by ajlouie** [sartography/cr-connect-frontend#68]
- [ ] At parent level, display subprocess name in left nav
- [ ] Once user clicks into the subprocess, the left nav lists sibling tasks within the subprocess, but not parent-level tasks
- [ ] Display breadcrumb navigation showing the ancestors of the subprocess

**Comment by danfunk** [comment]
outdated.  Based on current discussions there is no reason to make the end user aware that a subprocess was invoked.
