### ISSUE TITLE
Combine Docuement Sidebar and Data View

### ISSUE THREAD

**Issue by VictoriaSart** [sartography/cr-connect-frontend#80]
Rather than showing two icons we will show one icon that will allow the side drawer to come out. Once there if they have hte permission to see the Data View (i believe only configurators will have this in time) the toggle for data view would appear on the sidebar

<img width="1187" alt="Screen Shot 2020-05-12 at 5 04 24 PM" src="https://user-images.githubusercontent.com/64910981/81842746-8b7af180-951a-11ea-927e-f5460664dd7c.png">

**Comment by calexh-sar** [comment]
Closing as "will not do".
