### ISSUE TITLE
Add categories to CR Connect Task Sidebar

### ISSUE THREAD

**Issue by VictoriaSart** [sartography/cr-connect-frontend#81]
-We want to add categories for the sidebar so it is clearer to the user where the tasks they are working on lie in the entire process. 
-Tasks that have been completed will appear under "History" and will be shown in #666666, 
-Tasks that are active and available to edit will appear in the "Tasks" section and the active Task will appear as it does now
-Tasks that are possible for the future will appear in "Future section" in #666666

<img width="165" alt="Screen Shot 2020-05-13 at 1 07 31 PM" src="https://user-images.githubusercontent.com/64910981/81843088-1a880980-951b-11ea-85a9-f96d3dc89d9b.png">

**Comment by calexh-sar** [comment]
I think we should discuss this ticket further before any implementation.
